# Site settings
title: Kersten Broich Engineering
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering by Kersten Broich - Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.kersten-broich.de" # the base hostname & protocol for your site
twitter_username: kersten_broich
github_username:  Broich

# Build settings
markdown: kramdown
