# Site settings
title: Kersten Broich - Senior iOS Developer
email: k.broich@me.com
description: > # this means to ignore newlines until "baseurl:"
  Made in Berlin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: kersten_broich
github_username:  Broich

# Build settings
markdown: kramdown
