# Site settings
title: Kersten Broich - Software Developer And Maker
email: k.broich@me.com
description: > # this means to ignore newlines until "baseurl:"
  Made in Berlin
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://broich.github.io" # the base hostname & protocol for your site
twitter_username: kersten_broich
github_username:  Broich

# Build settings
markdown: kramdown
